#!/usr/bin/env bash
# description
_term() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	kill -9 "$(pgrep -f 100-process_and_pid_file)"
}

_int() {
	echo "Y U no love me?!"
}

_quit() {
	rm /var/run/myscript.pid
	kill -9 "$(pgrep -f 100-process_and_pid_file)"
}

trap _term SIGTERM

trap _int SIGINT

trap _quit SIGQUIT

echo "$BASHPID" > /var/run/myscript.pid

while :
do
echo "To infinity and beyond"
done
