#!/usr/bin/env bash
# i=1, while i is < or = to 10, it prints "Best School", checks if i = 9, and if i does = 9, it also prints "Hi", if i doesnt = 9, it doesnt, then it adds 1 to i before rerunning itself (it stops running once i is no longer < or = to 10)
i=1
while (( i<=10 ))
do
  echo "Best School"
  if ((i==9))
  then
    echo "Hi"
  fi
  ((++i))
done
