#!/usr/bin/env bash
# i=1, while i is < or = to 10, it checks if i = 4, if so, it prints "bad luck", if not, it then checks if i = 8, if so, it prints "good luck", if not, it prints "Best School", then, it adds 1 to i and reruns itself
i=1
while ((i<=10))
do
  if ((i==4))
  then
    echo "bad luck"
  elif ((i==8))
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((++i))
done
