#!/usr/bin/env bash
# i=1, while i is < or = 20, it prints the number that the variable i represents, and then checks if i = any of the listed strings (which are all numbers), and if so, it'll execute the command listed to be executed for that string before moving on, if i doesnt = any of the listed numbers, it moves on without doing anything, it then adds 1 to i and reruns itself
i=1
while ((i<=20))
do
  echo "$i"
  case "$i" in
    "4")  echo "bad luck from China"
    ;;
    "9")  echo "bad luck from Japan"
    ;;
    "17") echo "bad luck from Italy"
    ;;
  esac
  ((++i))
done
