#!/usr/bin/env bash
# m (representing minutes) = 1, h (representing hours) = 0, while h is < 13, it prints "Hour:" followed by the number that the variable h represents, then, while m < 60, if so, it prints the number that m represents and adds 1 to m before rerunning itself within the other while function, once m is no longer <60, that while statement stops rerunning itself and it continues to set m = to 1 as well as add 1 to h before rerunning itself
m=1
h=0
while ((h<13))
do
  echo "Hour: $h"
  while ((m<60))
  do
    echo "$m"
    ((++m))
  done
  ((m=1))
  ((++h))
done
